Batch02 = [
	# Strategy 0 – Completely wrong
	{ "item": { "input": "What is the derivative of x^2?", "reference": "The derivative of x^2 is 2x.", "output_text": "The derivative of x^2 is 2x^3." } }
	,{ "item": { "input": "Where does photosynthesis occur in living organisms?", "reference": "Photosynthesis occurs in the chloroplasts of plant cells and some protists.", "output_text": "Photosynthesis occurs in animal liver cells." } }
	,{ "item": { "input": "Explain recursion in programming.", "reference": "Recursion is when a function calls itself directly or indirectly to solve a problem.", "output_text": "Inflation affects currency value and purchasing power." } }
	,{ "item": { "input": "Who authored Hamlet?", "reference": "'Hamlet' was written by William Shakespeare.", "output_text": "The play was written by Charles Dickens." } }
	,{ "item": { "input": "What is GDP in economics?", "reference": "Gross Domestic Product is the total value of goods and services produced within a country's borders in a given period.", "output_text": "GDP is a headcount of the population." } }
	,{ "item": { "input": "Which organelle produces most cellular energy in eukaryotes?", "reference": "Mitochondria generate ATP and produce most cellular energy in eukaryotic cells.", "output_text": "The nucleus produces the cell's energy by breaking down glucose." } }
	,{ "item": { "input": "What does the law of supply and demand describe?", "reference": "It describes how prices emerge from the interaction of buyers and sellers as supply and demand change.", "output_text": "It explains how governments set prices by decree in all markets." } }
	,{ "item": { "input": "In Python, what is a function?", "reference": "A function is a reusable block of code that can accept arguments and return a value.", "output_text": "A function is a type of database table used to store rows." } }
	,{ "item": { "input": "Where in the cell does protein synthesis occur?", "reference": "Protein synthesis occurs on ribosomes in the cytoplasm or on the rough endoplasmic reticulum.", "output_text": "Proteins are synthesized inside lysosomes during digestion." } }
	,{ "item": { "input": "What is the speed of light in a vacuum?", "reference": "The speed of light in a vacuum is approximately 299,792,458 meters per second.", "output_text": "It depends on the color and is about 30,000 meters per second." } }

	# Strategy 1.1 – One correct fact embedded in wrong context
	,{ "item": { "input": "What role do mitochondria play in cells?", "reference": "Mitochondria generate ATP through cellular respiration, producing most of the cell's energy.", "output_text": "Mitochondria are found in cells and they store energy for later use." } }
	,{ "item": { "input": "What was the Industrial Revolution?", "reference": "A period of major industrialization from the late 18th to early 19th centuries that transformed economies through manufacturing and mechanization.", "output_text": "The Industrial Revolution was a time when people started working harder to make more money." } }
	# Strategy 1.2 – Accurate term, wrong explanation
	,{ "item": { "input": "How does the law of gravity work?", "reference": "The law of gravity states that two bodies are attracted to each other with a force proportional to their masses and inversely proportional to the square of the distance between them.", "output_text": "Gravity pulls objects down to the ground, but only if they are heavy." } }
	,{ "item": { "input": "Why is water essential for life?", "reference": "Water is essential for biochemical reactions, temperature regulation, nutrient transport, and waste removal.", "output_text": "Water keeps living things hydrated, but it does not play any role in chemical reactions." } }
	# Strategy 1.3 – Correct high-level conclusion, wrong specifics
	,{ "item": { "input": "What is a variable in programming?", "reference": "A variable is a named storage that holds data which can be changed during program execution.", "output_text": "A variable is a storage box, but it cannot be changed once created." } }
	,{ "item": { "input": "What is photosynthesis?", "reference": "A process in which plants use sunlight, carbon dioxide, and water to produce glucose and oxygen.", "output_text": "Photosynthesis is when plants grow by drinking water and eating soil." } }
	# Strategy 1.4 – Definition-only answer
	,{ "item": { "input": "What is the capital of France and its significance?", "reference": "Paris is the capital of France, serving as its political, cultural, and economic center.", "output_text": "Paris is a city in France where many people live, but it is not very important politically." } }
	,{ "item": { "input": "What does a compiler do?", "reference": "A compiler translates source code written in a programming language into machine code executable by a computer.", "output_text": "A compiler stores code for later use in a program." } }
	# Strategy 1.5 – Partial copy with major distortions
	,{ "item": { "input": "What is the main function of chlorophyll?", "reference": "Chlorophyll captures light energy for photosynthesis in plants.", "output_text": "Chlorophyll is a chemical that makes plants green, and it helps them stay warm in winter." } }
	,{ "item": { "input": "What is inflation in economics?", "reference": "Inflation is the rate at which the general level of prices for goods and services rises, eroding purchasing power.", "output_text": "Inflation is when the government prints money to pay workers more." } }

	# Strategy 2.1 – Two correct facts, others wrong
	,{ "item": { "input": "How does photosynthesis work in plants?", "reference": "Photosynthesis uses sunlight, carbon dioxide, and water to produce glucose and oxygen in chloroplasts.", "output_text": "Plants use sunlight and water to grow, but they also absorb minerals to create proteins and meat." } }
	,{ "item": { "input": "What are the main causes of World War I?", "reference": "Nationalism, imperialism, militarism, alliances, and the assassination of Archduke Franz Ferdinand.", "output_text": "Nationalism and alliances contributed, but the war mainly began due to oil shortages, space exploration, and television propaganda." } 
	# Strategy 2.2 – Accurate facts, wrong causal links
	,{ "item": { "input": "Why do economies experience inflation?", "reference": "Inflation can result from demand-pull effects, cost-push factors, and increases in the money supply.", "output_text": "Inflation happens when demand rises and when interest rates are high, which directly causes a drop in oxygen levels in the atmosphere." } }
	,{ "item": { "input": "Why do animals need oxygen?", "reference": "Oxygen is required for cellular respiration, a process that generates ATP for energy.", "output_text": "Animals need oxygen to breathe, which is why they can see better at night and grow faster in winter." } 
	# Strategy 2.3 – Correct detail + vague filler
	,{ "item": { "input": "How does the internet work?", "reference": "The internet works by transmitting data in packets through a network of routers and servers using standardized protocols.", "output_text": "The internet works with data packets and servers, but mostly it just happens through general computer connections and some other stuff." } }
	,{ "item": { "input": "What is the greenhouse effect?", "reference": "The greenhouse effect occurs when greenhouse gases trap heat in the Earth's atmosphere, warming the planet.", "output_text": "Greenhouse gases trap heat, but there’s also a lot going on in the air and nature that changes the weather." } 
	# Strategy 2.4 – Two correct points, partial terminology drift
	,{ "item": { "input": "What is DNA and what does it do?", "reference": "DNA stores genetic information and directs protein synthesis in cells.", "output_text": "DNA is a genetic blueprint and manages protein creation in organisms, but it also builds cell energy packs." } }
	,{ "item": { "input": "What is the role of the circulatory system?", "reference": "It transports oxygen, nutrients, hormones, and waste products throughout the body.", "output_text": "The blood transport network moves oxygen and food molecules but also repairs bones instantly when broken." } 
	# Strategy 2.5 – Two correct, others from adjacent but wrong topic
	,{ "item": { "input": "What are the primary functions of the nervous system?", "reference": "It processes information, controls bodily functions, and responds to stimuli.", "output_text": "It processes information and controls body movement, but also regulates digestion and produces red blood cells." } }
	,{ "item": { "input": "What is machine learning?", "reference": "Machine learning is a subset of AI that enables systems to learn from data and improve performance without being explicitly programmed.", "output_text": "Machine learning lets computers learn from data and also makes them think creatively like humans in dreams." } 

	# Strategy 3.1 – Three correct facts, two wrong
	,{ "item": { "input": "How does the water cycle operate?", "reference": "The water cycle includes evaporation, condensation, precipitation, infiltration, and runoff.", "output_text": "Water evaporates from surfaces, condenses into clouds, and falls as snow or rain, but it also directly teleports from oceans to rivers without precipitation and is stored forever in the sky." } }
	,{ "item": { "input": "What factors contributed to the fall of the Roman Empire?", "reference": "Economic troubles, overreliance on slave labor, military overspending, political corruption, and invasions by barbarian tribes.", "output_text": "Economic troubles, military overspending, and barbarian invasions played a role, but the empire also collapsed because citizens forgot the Latin language and all trade stopped overnight." } 
	# Strategy 3.2 – Accurate core but missing depth
	,{ "item": { "input": "What is quantum computing?", "reference": "Quantum computing uses principles of quantum mechanics, such as superposition and entanglement, to perform calculations much faster for certain problems.", "output_text": "Quantum computing uses quantum mechanics to calculate certain problems more quickly, but there’s not much else to it." } }
	,{ "item": { "input": "What is climate change?", "reference": "Climate change refers to long-term shifts in temperatures and weather patterns, primarily caused by human activities like burning fossil fuels.", "output_text": "Climate change is when global temperatures rise over time due to human activities, but that’s all there is to know." } 
	# Strategy 3.3 – Correct facts, one conclusion wrong
	,{ "item": { "input": "What causes tides on Earth?", "reference": "Tides are caused by the gravitational pull of the Moon and the Sun, along with the Earth's rotation.", "output_text": "Tides happen because of the Moon and Sun’s gravity, but they occur mainly to keep the oceans oxygenated for marine life." } }
	,{ "item": { "input": "Why do plants need nitrogen?", "reference": "Nitrogen is a vital nutrient for plants, used in amino acids, proteins, and chlorophyll production.", "output_text": "Plants need nitrogen to build proteins and chlorophyll, but mostly to help them grow taller than competing plants." } 
	# Strategy 3.4 – Terminology slip on one major term
	,{ "item": { "input": "What is the theory of evolution?", "reference": "The theory of evolution states that species change over generations through natural selection and genetic variation.", "output_text": "The theory of evolution says that species adapt over generations through organic selection and genetic mutation." } }
	,{ "item": { "input": "What is photosynthesis in detail?", "reference": "Photosynthesis is the process where plants use sunlight, water, and carbon dioxide to produce glucose and oxygen in chloroplasts.", "output_text": "Photosynthesis happens when plants use sunlight, water, and carbon dioxide to make sugar and air inside photochambers." } 
	# Strategy 3.5 – Correct but uneven coverage
	,{ "item": { "input": "What were the main achievements of the Apollo program?", "reference": "The Apollo program achieved human Moon landings, returned lunar samples, advanced space technology, inspired global interest, and expanded scientific knowledge.", "output_text": "The Apollo program landed people on the Moon, brought back samples, and inspired global interest, but it didn’t do much else." } }
	,{ "item": { "input": "What are the key functions of the human skeletal system?", "reference": "It provides structure, protects organs, anchors muscles, produces blood cells, and stores minerals.", "output_text": "The skeleton supports the body, protects vital organs, and helps movement, with less importance on the other things." } 

	# Strategy 4.1 – Four correct facts, one wrong
	,{ "item": { "input": "How do vaccines work?", "reference": "Vaccines stimulate the immune system to recognize and fight specific pathogens by introducing antigens without causing the disease.", "output_text": "Vaccines train the immune system to recognize and fight pathogens by introducing antigens, and they also permanently alter your DNA to resist all diseases." } }
	,{ "item": { "input": "What are the primary functions of the digestive system?", "reference": "It breaks down food, absorbs nutrients, eliminates waste, and supports immune function.", "output_text": "The digestive system breaks down food, absorbs nutrients, eliminates waste, and keeps the heart beating." } 
	# Strategy 4.2 – Four correct, one vague
	,{ "item": { "input": "How does the circulatory system support the body?", "reference": "It transports oxygen, nutrients, hormones, and waste products throughout the body.", "output_text": "The circulatory system moves oxygen, nutrients, hormones, and other things around the body." } }
	,{ "item": { "input": "What is the purpose of the United Nations?", "reference": "The UN promotes peace, protects human rights, fosters development, combats climate change, and provides humanitarian aid.", "output_text": "The United Nations promotes peace, protects human rights, fosters development, and does other helpful things." } 
	# Strategy 4.3 – Terminology slip for one fact
	,{ "item": { "input": "What is general relativity?", "reference": "General relativity is Einstein’s theory describing gravity as the warping of spacetime by mass and energy.", "output_text": "General relativity describes gravity as the bending of space-time fabric by matter and energy, known as graviton warping." } }
	,{ "item": { "input": "How does natural selection work?", "reference": "Natural selection is the process where organisms with advantageous traits survive and reproduce at higher rates, leading to evolutionary changes.", "output_text": "Natural selection happens when species with better traits survive and reproduce more, causing adaptational drift." } 
	# Strategy 4.4 – One minor unsupported claim
	,{ "item": { "input": "What is machine learning used for?", "reference": "Machine learning is used for pattern recognition, predictive analytics, natural language processing, computer vision, and recommendation systems.", "output_text": "Machine learning is used for recognizing patterns, making predictions, understanding language, analyzing images, recommending products, and controlling the weather." } }
	,{ "item": { "input": "How does the greenhouse effect influence climate?", "reference": "The greenhouse effect occurs when gases trap heat in the atmosphere, warming the planet and affecting climate patterns.", "output_text": "The greenhouse effect traps heat in the atmosphere, warming the planet and causing major earthquakes." } 
	# Strategy 4.5 – Missing minor detail in one fact
	,{ "item": { "input": "What is the role of the respiratory system?", "reference": "It brings oxygen into the body, expels carbon dioxide, and helps regulate blood pH.", "output_text": "The respiratory system brings oxygen into the body and removes carbon dioxide." } }
	,{ "item": { "input": "What are the benefits of renewable energy?", "reference": "Renewable energy reduces greenhouse gas emissions, decreases dependence on fossil fuels, promotes sustainability, creates jobs, and protects ecosystems.", "output_text": "Renewable energy reduces emissions, decreases fossil fuel use, promotes sustainability, and creates jobs." } 

	# Strategy 5.1 – Perfect paraphrase
	{ "item": { "input": "How does photosynthesis sustain plant life?", "reference": "Photosynthesis is the process where plants use sunlight, water, and carbon dioxide to produce glucose and oxygen in chloroplasts.", "output_text": "In plants, sunlight, water, and carbon dioxide are converted into glucose and oxygen within chloroplasts, a process that fuels their growth." } }
	,{ "item": { "input": "What is the function of the nervous system?", "reference": "The nervous system processes information, controls bodily functions, and responds to stimuli.", "output_text": "The nervous system interprets information, regulates the body’s activities, and reacts to internal and external changes." } 
	# Strategy 5.2 – Perfect but reordered
	,{ "item": { "input": "What is the greenhouse effect and its impact?", "reference": "The greenhouse effect occurs when gases trap heat in the atmosphere, warming the planet and affecting climate patterns.", "output_text": "By trapping heat in the atmosphere, greenhouse gases warm the planet and influence climate patterns worldwide." } }
	,{ "item": { "input": "What is DNA's role in living organisms?", "reference": "DNA stores genetic information and directs protein synthesis in cells.", "output_text": "DNA guides protein production in cells and serves as the repository of genetic instructions for life." } 
	# Strategy 5.3 – Perfect with synonyms
	,{ "item": { "input": "What is general relativity?", "reference": "General relativity is Einstein’s theory describing gravity as the warping of spacetime by mass and energy.", "output_text": "Einstein’s theory of general relativity explains gravity as the curvature of spacetime caused by the presence of mass and energy." } }
	,{ "item": { "input": "How does the circulatory system maintain life?", "reference": "It transports oxygen, nutrients, hormones, and waste products throughout the body.", "output_text": "The circulatory system moves oxygen, nutrients, hormones, and waste materials to keep the body functioning." } 
	# Strategy 5.4 – Perfect with minor expansion
	,{ "item": { "input": "What is the purpose of the United Nations?", "reference": "The UN promotes peace, protects human rights, fosters development, combats climate change, and provides humanitarian aid.", "output_text": "The United Nations works to maintain global peace, safeguard human rights, foster economic and social development, address climate challenges, and deliver humanitarian support in times of crisis." } }
	,{ "item": { "input": "What is machine learning?", "reference": "Machine learning is a subset of AI that enables systems to learn from data and improve performance without being explicitly programmed.", "output_text": "Machine learning is an area of AI in which systems improve their performance by analyzing data, without needing explicit programming for each task." } 
	# Strategy 5.5 – Perfect with varied emphasis
	,{ "item": { "input": "What are the benefits of renewable energy?", "reference": "Renewable energy reduces greenhouse gas emissions, decreases dependence on fossil fuels, promotes sustainability, creates jobs, and protects ecosystems.", "output_text": "By cutting greenhouse gas emissions and reducing reliance on fossil fuels, renewable energy supports sustainability, generates employment, and safeguards ecosystems." } }
	,{ "item": { "input": "What is the role of the respiratory system?", "reference": "It brings oxygen into the body, expels carbon dioxide, and helps regulate blood pH.", "output_text": "The respiratory system supplies oxygen to the body, removes carbon dioxide, and assists in maintaining the proper pH balance in the blood." } 

]
